name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: devops-demo-app
  PUSHGATEWAY_METRIC: ci_pipeline_runs_total

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set build vars
        id: vars
        run: |
          SHA_SHORT=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "TAG=${SHA_SHORT}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

      - name: Push CI "run" metric to Pushgateway (start)
        run: |
          echo "${{ env.PUSHGATEWAY_METRIC }}{repo=\"${{ github.repository }}\"} 1" | \
          curl --data-binary @- http://${{ secrets.EC2_HOST }}:9091/metrics/job/builds/instance/${{ github.run_id }}

      - name: SSH deploy (pull & restart stack)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.EC2_PROJECT_DIR }}/monitoring
            docker compose pull app
            docker compose up -d

      - name: Push CI duration metric to Pushgateway (end)
        if: always()
        run: |
          DUR=$(( $(date +%s) - $(date -d "${{ github.event.head_commit.timestamp }}" +%s) ))
          cat <<EOF | curl --data-binary @- http://${{ secrets.EC2_HOST }}:9091/metrics/job/builds/instance/${{ github.run_id }}
          ci_last_build_duration_seconds ${DUR}
          ci_build_success{status="${{ job.status }}"} 1
          EOF
