{
 "title": "DevOps Observability",
 "refresh": "10s",
 "panels": [
  {
   "title": "Builds (Last 24h)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(increase(ci_pipeline_runs_total[24h]))"
    }
   ]
  },
  {
   "title": "Build Duration (s)",
   "type": "timeSeries",
   "gridPos": { "x": 6, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "ci_last_build_duration_seconds" }
   ]
  },
  {
   "title": "App Request Rate",
   "type": "timeSeries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(app_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "App Latency (p95)",
   "type": "timeSeries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le, endpoint))"
    }
   ]
  },
  {
   "title": "CPU Usage (node)",
   "type": "timeSeries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage (node)",
   "type": "timeSeries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  }
 ]
}